"""
Custom LLM integration template for the Question Paper Generator.
═══════════════════════════════════════════════════════════════════

HOW TO USE
──────────
1. Copy this file to  ``custom_llm.py``  in the same directory.
2. Replace the ``generate()`` function below with your own LLM logic.
3. In the Streamlit app, select **"Custom Built LLM (No API)"** from the
   LLM Provider dropdown — that's it.  No API key, no server, no internet.

For the CLI (generate_paper.py):

    LLM_PROVIDER=custom_callable python generate_paper.py

    # Or point to a different file / module:
    LLM_CUSTOM_MODULE=/absolute/path/to/my_llm.py python generate_paper.py

INTERFACE CONTRACT
──────────────────
Your file must expose exactly ONE public name:

    generate(prompt: str) -> str

``generate`` can be a plain function, a bound method, or any callable
object (e.g. a class instance with ``__call__``).  It receives the full
conversation history as a single formatted string and must return the
model's reply as a plain string.

The function is called in the same process as the Streamlit app or CLI
script — no subprocess, no network socket, no API key needed.
"""

# ---------------------------------------------------------------------------
# 1.  Import your custom model here
# ---------------------------------------------------------------------------
# Example imports — replace with whatever your model needs:
#
#   import torch
#   from my_package import MyFinetunedModel
#
# For this demonstration we use a very simple keyword-based stub that
# produces readable output without any external dependency.

import re
import textwrap


# ---------------------------------------------------------------------------
# 2.  Load / initialise your model ONCE at module-import time.
#     Keep this outside `generate()` so the model is only loaded once.
# ---------------------------------------------------------------------------

class _DemoModel:
    """
    Minimal stub that returns canned responses — replace with your real model.

    A real implementation might look like:

        class _DemoModel:
            def __init__(self):
                self.tokenizer = AutoTokenizer.from_pretrained("/models/my-llm")
                self.model     = AutoModelForCausalLM.from_pretrained("/models/my-llm")

            def infer(self, prompt: str) -> str:
                inputs  = self.tokenizer(prompt, return_tensors="pt")
                outputs = self.model.generate(**inputs, max_new_tokens=512)
                return self.tokenizer.decode(outputs[0], skip_special_tokens=True)
    """

    def infer(self, prompt: str) -> str:  # noqa: D401
        """Stub inference — replace with real model logic."""
        # Detect the task from key phrases in the prompt
        p = prompt.lower()

        if "exam pattern" in p or "sample paper" in p or "analyze" in p:
            return textwrap.dedent("""\
                **Exam Pattern (extracted by custom LLM)**

                - **Total Marks:** 100
                - **Duration:** 3 Hours
                - **Section A:** 10 × 2 = 20 marks (compulsory short answers)
                - **Section B:** 5 questions, attempt any 4 × 10 = 40 marks
                - **Section C:** 3 questions, attempt any 2 × 20 = 40 marks
            """)

        if "module" in p or "syllabus" in p or "hours" in p or "json" in p:
            return '{"Module 1: Introduction": 8, "Module 2: Core Concepts": 10, "Module 3: Applications": 12}'

        if "question paper" in p or "generate" in p or "exam" in p:
            return textwrap.dedent("""\
                # Question Paper (generated by custom LLM)

                **Duration:** 3 Hours  |  **Max Marks:** 100

                ## Section A — Short Answer (2 marks each, attempt all 10)

                1. Define the key concept of Module 1.
                2. List two applications discussed in Module 3.
                3. What is the significance of Module 2 in this subject?
                *(… and so on)*

                ## Section B — Medium Answer (10 marks each, attempt any 4)

                1. Explain the core principles of Module 2 with examples.
                2. Compare and contrast the approaches in Module 1 and Module 3.
                *(… and so on)*

                ## Section C — Long Answer (20 marks each, attempt any 2)

                1. Critically evaluate the role of Module 3 in real-world scenarios.
                2. Discuss the evolution of Module 1 and its impact on modern practices.
                *(… and so on)*
            """)

        # Generic fallback
        return "Custom LLM response: (replace this stub with your real model output)"


_model = _DemoModel()


# ---------------------------------------------------------------------------
# 3.  Define `generate` — the only function the app cares about.
# ---------------------------------------------------------------------------

def generate(prompt: str) -> str:
    """
    Entry point called by the Question Paper Generator.

    Args:
        prompt: The full formatted prompt string, including system instructions
                and user content concatenated by the LangChain pipeline.

    Returns:
        The model's response as a plain string.
    """
    return _model.infer(prompt)
